######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 17 14:34:47 2010
######################################################################


# ============================================================================
#  Name        : QtGSTPlayer.pro
#  Part of     : LibHb / gstplayer
#  Description : Project definition file for simple gstplayer
#  Version     : %version: 1 %
#
#  Copyright ? 2008 Nokia.  All rights reserved.
#  This material, including documentation and any related computer
#  programs, is protected by copyright controlled by Nokia.  All
#  rights are reserved.  Copying, including reproducing, storing,
#  adapting or translating, any or all of this material requires the
#  prior written consent of Nokia.  This material also contains
#  confidential information which may not be disclosed to others
#  without the prior written consent of Nokia.
# ============================================================================
#

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp folderview.cpp views.cpp record_play.c
HEADERS += folderview.h views.h

RESOURCES += QtGSTPlayer.qrc

